name:                bfi
version:             0.1.0.0
github:              "d2xci8xc5/bfi"
license:             BSD3
author:              "d2ci8xc5"
maintainer:          "d2ci8xc5@tuta.io"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bfi-exe:
    main:                Main.hs
    source-dirs:         src 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bfi

tests:
  bfi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bfi
